### ISSUE TITLE
Documentation tweak for pip installation

### ISSUE THREAD

**Issue by vinceskahan** [weewx/weewx#1012]
(ref: Graham's thread from Sept-1-2025 re: upgrading the os from bookworm to trixie)

For a pip install, the instructions say to use "**python3 -m venv**" which specifies the operating system's default version of python.  The venv then will use that /usr/bin/python3 path in the venv setup, and the weewx service files created by setup-daemon.sh will do so as well.

The result is that while the underlying 'libs' and systemd service files will specify python3.11, the python3 and pip versions the venv and service files resolve to will float with the os defaults.  This causes breakage if the os 'then' upgrades from that version of python to a newer version.  

The fix is to procedurally create the venv with a 'specific' version of python ala "**python3.11 -m venv**" which will fully hard-pin the version to the one the user wants.  At that point everything end-to-end will be os-upgrade-safe as long as the specified version of python+pip are present on the system.

Suggest a minor tweak to the quickstart docs and/or a pointer to a new wiki page about venv nuances.

**Comment by grider3149** [comment]
Maybe this helps.
https://droplink.digital/file/1eb3161d3cbbf0e4fd76347a869b649e

**Comment by tkeffer** [comment]
I'm not sure that would help because, in this case, the old Python libraries under `/usr/lib/python3.11` get wiped out.

Really, one should rebuild the virtual environment after a major upgrade.

It's always risky to do an *in situ* upgrade to a major OS release. I try to avoid it.

**Comment by tkeffer** [comment]
Fixed in commit https://github.com/weewx/weewx/commit/b359691bb59fcc0385808ca98ed847ea4951d26c

**Comment by vinceskahan** [comment]
FWIW I just retested and the full os dist-upgrade did ‘not’ remove the old
system level 3.11 dpkgs nor the contents of the original 3.11-based python
libs within the venv. It just added new os level packages and changed the
os default.

Agree about generally not doing major os upgrades rather than clean
installations, but testing confirms that  if the venv specifies an absolute
python version then doing so seems doable without risk. I guess that’s
kinda the venv mantra as I understand it.

-----  ***@***.*** ----

**Comment by tkeffer** [comment]
I did the same, following the [Debian instructions](https://www.debian.org/releases/trixie/release-notes/upgrading.html), and it did remove all the Python 3.11 libraries.

```
$ ls -ald /usr/lib/py*
drwxr-xr-x  3 root root  4096 May 12 17:08 /usr/lib/python3
drwxr-xr-x 37 root root 12288 Sep  1 13:56 /usr/lib/python3.13
```

**Comment by vinceskahan** [comment]
Doesn't matter. Copies are physically in the venv aren't they ?

-----  ***@***.*** ----

**Comment by vinceskahan** [comment]
Again - I created the venv specifying 3.11 but yes I got symlinks

```
(weewx-venv) vagrant@bookworm:~/weewx-venv/bin$ ls -ald ~/weewx-venv/bin/pyt*
lrwxrwxrwx 1 vagrant vagrant 10 Sep  1 22:13 /home/vagrant/weewx-venv/bin/python -> python3.11
lrwxrwxrwx 1 vagrant vagrant 10 Sep  1 22:13 /home/vagrant/weewx-venv/bin/python3 -> python3.11
lrwxrwxrwx 1 vagrant vagrant 19 Sep  1 22:13 /home/vagrant/weewx-venv/bin/python3.11 -> /usr/bin/python3.11
```

But that part doesn't matter if what they point to are still present (they are), and all the libs in the venv are still present (they are).

```
weewx-venv) vagrant@bookworm:~/weewx-venv/bin$ pip3 list --verbose
Package    Version Location                                              Installer
---------- ------- ----------------------------------------------------- ---------
configobj  5.0.9   /home/vagrant/weewx-venv/lib/python3.11/site-packages pip
CT3        3.4.0   /home/vagrant/weewx-venv/lib/python3.11/site-packages pip
ephem      4.2     /home/vagrant/weewx-venv/lib/python3.11/site-packages pip
pillow     11.3.0  /home/vagrant/weewx-venv/lib/python3.11/site-packages pip
pip        23.0.1  /home/vagrant/weewx-venv/lib/python3.11/site-packages pip
PyMySQL    1.1.2   /home/vagrant/weewx-venv/lib/python3.11/site-packages pip
pyserial   3.5     /home/vagrant/weewx-venv/lib/python3.11/site-packages pip
pyusb      1.3.1   /home/vagrant/weewx-venv/lib/python3.11/site-packages pip
setuptools 66.1.1  /home/vagrant/weewx-venv/lib/python3.11/site-packages pip
weewx      5.1.0   /home/vagrant/weewx-venv/lib/python3.11/site-packages pip
```

**Comment by tkeffer** [comment]
Hmmm, on my system `/usr/bin/python3.11` is gone. There's just `/usr/bin/python3.13`.

Obviously, there are too many variations to reliably suggest an upgrade path. Better to say "rebuild the venv."

**Comment by vinceskahan** [comment]
Fair enough. Heaven knows what redhatish update would do.

-----  ***@***.*** ----
