### ISSUE TITLE
Non-positive value for record field 'interval': 0 on WMR200

### ISSUE THREAD

**Issue by SuddenlyQ** [weewx/weewx#375]
I fixed this by changing the value `if timestamp_packet_interval <= 0`  in /usr/share/weewx/weewx/drivers/wmr200.py from 0 to 1.

**Comment by tkeffer** [comment]
Thanks, but I have 2 questions:

1. What problem did this fix? Were you having duplicate records? Something else?

2. The original line of code rejected values less than zero (not less than or equal to zero). What does the final code look like? This?

   ```python
                if timestamp_packet_interval <= 1:
                    loginf(('genStartup() Discarding received archive record that presented out-of-order; '
                            'current timestamp:%s; previous timestamp:%s')
                           % (weeutil.weeutil.timestamp_to_string(timestamp_packet_current),
                              weeutil.weeutil.timestamp_to_string(timestamp_packet_previous)))
   ```

**Comment by SuddenlyQ** [comment]
1. weeWX was failing with an error about non-postive values for interval. I believe I changed it to be < 1 or <= 0.

**Comment by tkeffer** [comment]
My apologies, but I'm still not understanding. If it encounters a non-positive interval, WeeWX should just reject it, not fail. Could you please post a system log where it was failing?

And, I would appreciate it if you could be more specific whether the comparison is

```python
if timestamp_packet_interval <= 0`
```
or
```python
if timestamp_packet_interval < 1`
```

**Comment by SuddenlyQ** [comment]
Here's a syslog:
```
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: MainThread: I Using pc time adjusting archive record time by 38 sec 2018-01-26 20:51:00 PST (1517028660) => 2018-01-26 20:51:38 PST (1517028698)
Feb 15 08:44:06 raspberrypi weewx[17790]: manager: Added record 2018-01-26 20:51:38 PST (1517028698) to database 'weewx.sdb'
Feb 15 08:44:06 raspberrypi weewx[17790]: engine: Main loop exiting. Shutting engine down.
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: Thread-2: I USB polling device thread exiting
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: MainThread: I USB polling thread expired
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: Thread-1: I Watchdog received shutdown
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: Thread-1: I Watchdog thread exiting
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: MainThread: I Watchdog thread expired
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: MainThread: I Received packet count live:6 archive:1 control:2
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: MainThread: I Received bytes:816 sent bytes:56
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: MainThread: I Packet archive queue len:0 live queue len:6
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: MainThread: W Exiting with packets still in live queue cnt:6
Feb 15 08:44:06 raspberrypi weewx[17790]: wmr200: MainThread: I Driver gracefully exiting
Feb 15 08:44:06 raspberrypi weewx[17790]: engine: Caught unrecoverable exception in engine:
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****  Non-positive value for record field 'interval': 0
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****  Traceback (most recent call last):
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****    File "/usr/share/weewx/weewx/engine.py", line 890, in main
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****      engine.run()
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****    File "/usr/share/weewx/weewx/engine.py", line 160, in run
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****      self.dispatchEvent(weewx.Event(weewx.STARTUP))
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****      callback(event)
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****    File "/usr/share/weewx/weewx/engine.py", line 520, in startup
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****      self._catchup(self.engine.console.genStartupRecords)
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****    File "/usr/share/weewx/weewx/engine.py", line 635, in _catchup
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****      origin='hardware'))
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****      callback(event)
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****    File "/usr/share/weewx/weewx/engine.py", line 601, in new_archive_record
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****      dbmanager.addRecord(event.record, accumulator=self.old_accumulator)
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****    File "/usr/share/weewx/weewx/manager.py", line 246, in addRecord
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****      self._addSingleRecord(record, cursor, log_level)
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****    File "/usr/share/weewx/weewx/manager.py", line 1212, in _addSingleRecord
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****      _weight = self._calc_weight(record)
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****    File "/usr/share/weewx/weewx/manager.py", line 1582, in _calc_weight
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****      raise ValueError("Non-positive value for record field 'interval': %s" % (record['interval'], ))
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****  ValueError: Non-positive value for record field 'interval': 0
Feb 15 08:44:06 raspberrypi weewx[17790]:     ****  Exiting.
```

And here's the comparison:
```              
  if timestamp_packet_interval < 1:
                    loginf(('genStartup() Discarding received archive record that presented out-of-order; '
                            'current timestamp:%s; previous timestamp:%s')
                           % (weeutil.weeutil.timestamp_to_string(timestamp_packet_current),
                              weeutil.weeutil.timestamp_to_string(timestamp_packet_previous)))
```

**Comment by tkeffer** [comment]
Fixed in commit https://github.com/weewx/weewx/commit/7ccb1345cc0831bae7df46266ee79f7b0b8c3b59

Thank you for your patience! I just wanted to make sure we were actually fixing the problem

**Comment by superhet70** [comment]
I too have this problem with a WMR200. 
How does changing the timestamp_packet_interval in wmr200.py fix this issue when the error comes from manager.py? I changed wmr200.py a few months ago and the problem still pops up intermittently. I have now change line 1582 in manager.py and will wait and see if it happens again.

**Comment by mdecker** [comment]
I have the same issue on WMR200. It happens very irregularly. Before a crash yesterday it ran for months.  I manually changed the code according to commit 7ccb134. That did not help, however. Just last night I had another crash. So I suspect that this does not fix the issue, unfortunately.

> Sep 14 17:56:54 vega weewx[31271]: engine: Main loop exiting. Shutting engine down.
> Sep 14 17:56:54 vega weewx[31271]: wmr200: Thread-4: I USB polling device thread exiting
> Sep 14 17:56:54 vega weewx[31271]: wmr200: MainThread: I USB polling thread expired
> Sep 14 17:56:54 vega weewx[31271]: wmr200: Thread-3: I Watchdog received shutdown
> Sep 14 17:56:54 vega weewx[31271]: wmr200: Thread-3: I Watchdog thread exiting
> Sep 14 17:56:54 vega weewx[31271]: wmr200: MainThread: I Watchdog thread expired
> Sep 14 17:56:54 vega weewx[31271]: wmr200: MainThread: I Received packet count live:21870 archive:971 control:1758
> Sep 14 17:56:54 vega weewx[31271]: wmr200: MainThread: I Received bytes:976 sent bytes:48
> Sep 14 17:56:54 vega weewx[31271]: wmr200: MainThread: I Packet archive queue len:0 live queue len:4
> Sep 14 17:56:54 vega weewx[31271]: wmr200: MainThread: W Exiting with packets still in live queue cnt:4
> Sep 14 17:56:54 vega weewx[31271]: wmr200: MainThread: I Driver gracefully exiting
> Sep 14 17:56:54 vega weewx[31271]: engine: Caught unrecoverable exception in engine:
> Sep 14 17:56:54 vega weewx[31271]:     ****  Non-positive value for record field 'interval': 0
> Sep 14 17:56:54 vega weewx[31271]:     ****  Traceback (most recent call last):
> Sep 14 17:56:54 vega weewx[31271]:     ****    File "/usr/share/weewx/weewx/engine.py", line 890, in main
> Sep 14 17:56:54 vega weewx[31271]:     ****      engine.run()
> Sep 14 17:56:54 vega weewx[31271]:     ****    File "/usr/share/weewx/weewx/engine.py", line 160, in run
> Sep 14 17:56:54 vega weewx[31271]:     ****      self.dispatchEvent(weewx.Event(weewx.STARTUP))
> Sep 14 17:56:54 vega weewx[31271]:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
> Sep 14 17:56:54 vega weewx[31271]:     ****      callback(event)
> Sep 14 17:56:54 vega weewx[31271]:     ****    File "/usr/share/weewx/weewx/engine.py", line 520, in startup
> Sep 14 17:56:54 vega weewx[31271]:     ****      self._catchup(self.engine.console.genStartupRecords)
> Sep 14 17:56:54 vega weewx[31271]:     ****    File "/usr/share/weewx/weewx/engine.py", line 635, in _catchup
> Sep 14 17:56:54 vega weewx[31271]:     ****      origin='hardware'))
> Sep 14 17:56:54 vega weewx[31271]:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
> Sep 14 17:56:54 vega weewx[31271]:     ****      callback(event)
> Sep 14 17:56:54 vega weewx[31271]:     ****    File "/usr/share/weewx/weewx/engine.py", line 601, in new_archive_record
> Sep 14 17:56:54 vega weewx[31271]:     ****      dbmanager.addRecord(event.record, accumulator=self.old_accumulator)
> Sep 14 17:56:54 vega weewx[31271]:     ****    File "/usr/share/weewx/weewx/manager.py", line 246, in addRecord
> Sep 14 17:56:54 vega weewx[31271]:     ****      self._addSingleRecord(record, cursor, log_level)
> Sep 14 17:56:54 vega weewx[31271]:     ****    File "/usr/share/weewx/weewx/manager.py", line 1212, in _addSingleRecord
> Sep 14 17:56:54 vega weewx[31271]:     ****      _weight = self._calc_weight(record)
> Sep 14 17:56:54 vega weewx[31271]:     ****    File "/usr/share/weewx/weewx/manager.py", line 1582, in _calc_weight
> Sep 14 17:56:54 vega weewx[31271]:     ****      raise ValueError("Non-positive value for record field 'interval': %s" % (record['interval'], ))
> Sep 14 17:56:54 vega weewx[31271]:     ****  ValueError: Non-positive value for record field 'interval': 0
> Sep 14 17:56:54 vega weewx[31271]:     ****  Exiting.

**Comment by tkeffer** [comment]
Michael, could you try this fix? https://github.com/cmanton/weewx/commit/47800a0a622b7931898faf5aa6b254cac943557a

**Comment by mdecker** [comment]
thanks for the hint. I replaced my wmr200.py with the one from cmanton@47800a0 and will report

**Comment by mdecker** [comment]
@cmanton there seems to be a typo or misconception in your fix. My weewx tripped into this last night. It looks to me like `timestamp_packet_previous += self.wmr200.time_drift` it should maybe be 
`timestamp_packet_previous += self.time_drift`?

```
Sep 20 05:32:21 vega weewx[15035]: engine: Caught unrecoverable exception in engine:
Sep 20 05:32:21 vega weewx[15035]:     ****  'WMR200' object has no attribute 'wmr200'
Sep 20 05:32:21 vega weewx[15035]:     ****  Traceback (most recent call last):
Sep 20 05:32:21 vega weewx[15035]:     ****    File "/usr/share/weewx/weewx/engine.py", line 890, in main
Sep 20 05:32:21 vega weewx[15035]:     ****      engine.run()
Sep 20 05:32:21 vega weewx[15035]:     ****    File "/usr/share/weewx/weewx/engine.py", line 160, in run
Sep 20 05:32:21 vega weewx[15035]:     ****      self.dispatchEvent(weewx.Event(weewx.STARTUP))
Sep 20 05:32:21 vega weewx[15035]:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
Sep 20 05:32:21 vega weewx[15035]:     ****      callback(event)
Sep 20 05:32:21 vega weewx[15035]:     ****    File "/usr/share/weewx/weewx/engine.py", line 520, in startup
Sep 20 05:32:21 vega weewx[15035]:     ****      self._catchup(self.engine.console.genStartupRecords)
Sep 20 05:32:21 vega weewx[15035]:     ****    File "/usr/share/weewx/weewx/engine.py", line 632, in _catchup
Sep 20 05:32:21 vega weewx[15035]:     ****      for record in generator(lastgood_ts):
Sep 20 05:32:21 vega weewx[15035]:     ****    File "/usr/share/weewx/weewx/drivers/wmr200.py", line 1940, in genStartupRecords
Sep 20 05:32:21 vega weewx[15035]:     ****      timestamp_packet_previous += self.wmr200.time_drift
Sep 20 05:32:21 vega weewx[15035]:     ****  AttributeError: 'WMR200' object has no attribute 'wmr200'
Sep 20 05:32:21 vega weewx[15035]:     ****  Exiting.

```

**Comment by cmanton** [comment]
Hi Michael,

Thanks for testing...my wmr200 has died and I replaced with another
vendor/model.

The failure is WMR200 *is* the object scope, but then the code tries to
access wmr200 which is already available; so the variable 'path' is
incorrect.

I've included a patch to overlay on the one you've already applied to
address this issue.

thx,

Chris
--

**Comment by tkeffer** [comment]
@cmanton Unfortunately, users are still getting this problem, so I'm reopening. Could you investigate?

**Comment by cmanton** [comment]
Initial recommendation is to disable the archive feature on the wmr200 model and only process live packets.

erase_archive=true

Is there a recent bug report ?

**Comment by tkeffer** [comment]
@cmanton Yes. Here's the thread: https://groups.google.com/forum/#!topic/weewx-user/WFDP08JI0E8

**Comment by tkeffer** [comment]
Hopefully fixed for good!

**Comment by Adri1G** [comment]
I had this crash on my weewx installation, normally with the latest version of weewx (3.9.2).

This is from wee_debug --info
```
Using configuration file /etc/weewx/weewx.conf
Using database binding 'wx_binding', which is bound to database 'archive_sqlite'

System info
  Platform:       Linux-4.19.97-v7+-armv7l-with-debian-10.3
  Python Version: 2.7.16

Load Information
  1 minute load average:  0.08
  5 minute load average:  0.02
  15 minute load average: 0.01

General Weewx info
  Weewx version 3.9.2 detected.

Station info
  Station type: WMR200
  Driver:       weewx.drivers.wmr200

Driver info
[WMR200]
    # This section is for the Oregon Scientific WMR200

    # The station model, e.g., WMR200, WMR200A, Radio Shack W200
    model = WMR200

    # The driver to use:
    driver = weewx.drivers.wmr200

Currently installed extensions
Extension Name    Version   Description
cmon              0.16      Collect and display computer health indicators.

Archive info
  Database name:        weewx.sdb
  Table name:           archive
  Version               2.0
  Unit system:          1 (US)
  First good timestamp: 2020-04-05 15:58:00 CEST (1586095080)
  Last good timestamp:  2020-04-08 02:07:00 CEST (1586304420)
  Number of records:    3450
  weewx (weewx.conf) is set to use an archive interval of 300 seconds.
  The station hardware was not interrogated in determining archive interval.

Databases configured in weewx.conf
  Database name:        weewx.sdb
  Database driver:      weedb.sqlite

  Database name:        weewx
  Database driver:      weedb.mysql
  Database host:        localhost

  Database name:        cmon.sdb
  Database driver:      weedb.sqlite
```

This is from syslog
```
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: Thread-2: E read_device() USB Error Reason:[Errno 110] Operation timed out
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: Thread-2: E USB device read error
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: MainThread: E USB polling thread unexpectedly terminated
Apr  8 02:08:03 raspberrypi weewx[566]: engine: Main loop exiting. Shutting engine down.
Apr  8 02:08:03 raspberrypi weewx[566]: engine: Shutting down StdReport thread
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: MainThread: I USB polling thread expired
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: Thread-1: I Watchdog received shutdown
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: Thread-1: I Watchdog thread exiting
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: MainThread: I Watchdog thread expired
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: MainThread: I Received packet count live:4463 archive:0 control:464
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: MainThread: I Received bytes:494936 sent bytes:10928
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: MainThread: I Packet archive queue len:0 live queue len:0
Apr  8 02:08:03 raspberrypi weewx[566]: wmr200: MainThread: I Driver gracefully exiting
Apr  8 02:08:04 raspberrypi weewx[566]: engine: Caught WeeWxIOError: USB polling thread unexpectedly terminated
Apr  8 02:08:04 raspberrypi weewx[566]:     ****  Waiting 60 seconds then retrying...
Apr  8 02:09:04 raspberrypi weewx[566]: engine: retrying...
Apr  8 02:09:04 raspberrypi weewx[566]: engine: Using configuration file /etc/weewx/weewx.conf
Apr  8 02:09:04 raspberrypi weewx[566]: engine: Loading station type WMR200 (weewx.drivers.wmr200)
Apr  8 02:09:04 raspberrypi weewx[566]: wmr200: MainThread: I driver version is 3.3.5
Apr  8 02:09:04 raspberrypi weewx[566]: wmr200: MainThread: I sensor map is {'outTempBatteryStatus': 'battery_status_out', 'outHumidity': 'humidity_1', 'rainRate': 'rain_rate', 'heatindex4'
: 'heatindex_5', 'rainTotal': 'rain_total', 'rainBatteryStatus': 'battery_status_rain', 'heatindex6': 'heatindex_7', 'extraTemp5': 'temperature_6', 'uvFault': 'uv_fault', 'extraTemp2': 'tem
perature_3', 'heatindex': 'heatindex_1', 'extraTemp3': 'temperature_4', 'rain24': 'rain_24', 'inHeatindex': 'heatindex_0', 'inTemp': 'temperature_0', 'extraTemp1': 'temperature_2', 'hourRai
n': 'rain_hour', 'windFault': 'wind_fault', 'windchill': 'windchill', 'clockUnsynchronized': 'clock_unsynchronized', 'extraTemp7': 'temperature_8', 'rain': 'rain', 'forecastIcon': 'forecast
_icon', 'pressure': 'pressure', 'extraHumid4': 'humidity_5', 'extraHumid5': 'humidity_6', 'extraHumid2': 'humidity_3', 'extraHumid3': 'humidity_4', 'extraHumid1': 'humidity_2', 'extraTemp6'
: 'temperature_7', 'heatindex5': 'heatindex_6', 'extraTemp4': 'temperature_5', 'heatindex7': 'heatindex_8', 'altimeter': 'altimeter', 'heatindex1': 'heatindex_2', 'heatindex2': 'heatindex_3
', 'heatindex3': 'heatindex_4', 'extraHumid6': 'humidity_7', 'extraHumid7': 'humidity_8', 'windBatteryStatus': 'battery_status_wind', 'UV': 'uv', 'rainFault': 'rain_fault', 'windDir': 'wind
_dir', 'outTemp': 'temperature_1', 'windSpeed': 'wind_speed', 'inHumidity': 'humidity_0', 'outTempFault': 'out_fault', 'windGust': 'wind_gust', 'uvBatteryStatus': 'battery_status_uv'}
Apr  8 02:09:04 raspberrypi weewx[566]: wmr200: MainThread: I Created watchdog thread to poke for live data every 30 seconds
Apr  8 02:09:04 raspberrypi weewx[566]: wmr200: MainThread: I Created USB polling thread to read block on device
Apr  8 02:09:04 raspberrypi weewx[566]: wmr200: Thread-4: I USB polling device thread for live data launched
Apr  8 02:09:04 raspberrypi weewx[566]: wmr200: MainThread: I Reset console device
Apr  8 02:09:05 raspberrypi weewx[566]: wmr200: Thread-4: I USB polling device thread signaled to start
Apr  8 02:09:05 raspberrypi weewx[566]: wmr200: Thread-3: I Started watchdog thread live data
Apr  8 02:09:05 raspberrypi weewx[566]: wmr200: MainThread: W Restart count: 2
Apr  8 02:09:05 raspberrypi weewx[566]: engine: StdConvert target unit is 0x1
Apr  8 02:09:05 raspberrypi weewx[566]: wxcalculate: The following values will be calculated: barometer=prefer_hardware, windchill=hardware, dewpoint=prefer_hardware, appTemp=prefer_hardwar
e, rainRate=hardware, windrun=prefer_hardware, heatindex=hardware, maxSolarRad=prefer_hardware, humidex=prefer_hardware, pressure=prefer_hardware, inDewpoint=prefer_hardware, ET=prefer_hard
ware, altimeter=prefer_hardware, cloudbase=prefer_hardware
Apr  8 02:09:05 raspberrypi weewx[566]: wxcalculate: The following algorithms will be used for calculations: altimeter=aaNOAA, maxSolarRad=RS
Apr  8 02:09:05 raspberrypi weewx[566]: engine: Archive will use data binding wx_binding
Apr  8 02:09:05 raspberrypi weewx[566]: engine: Record generation will be attempted in 'hardware'
Apr  8 02:09:05 raspberrypi weewx[566]: engine: The archive interval in the configuration file (300) does not match the station hardware interval (60).
Apr  8 02:09:05 raspberrypi weewx[566]: engine: Using archive interval of 60 seconds (specified by hardware)
Apr  8 02:09:05 raspberrypi weewx[566]: engine: Using binding 'wx_binding' to database 'weewx.sdb'
Apr  8 02:09:05 raspberrypi weewx[566]: manager: Starting backfill of daily summaries
Apr  8 02:09:05 raspberrypi weewx[566]: restx: StationRegistry: Registration not requested.
Apr  8 02:09:05 raspberrypi weewx[566]: restx: Wunderground: Posting not enabled.
Apr  8 02:09:05 raspberrypi weewx[566]: restx: PWSweather: Posting not enabled.
Apr  8 02:09:05 raspberrypi weewx[566]: restx: CWOP: Posting not enabled.
Apr  8 02:09:05 raspberrypi weewx[566]: restx: WOW: Posting not enabled.
Apr  8 02:09:05 raspberrypi weewx[566]: restx: AWEKAS: Posting not enabled.
Apr  8 02:09:05 raspberrypi weewx[566]: engine: Starting up weewx version 3.9.2
Apr  8 02:09:08 raspberrypi weewx[566]: wmr200: MainThread: I genStartup() Delaying archive packet processing until live packet received
Apr  8 02:09:08 raspberrypi weewx[566]: wmr200: MainThread: I genStartup() Delaying archive packet processing until live packet received
Apr  8 02:09:08 raspberrypi weewx[566]: wmr200: MainThread: I genStartup() Delaying archive packet processing until live packet received
Apr  8 02:09:08 raspberrypi weewx[566]: wmr200: MainThread: I Time drift between host and console in seconds:8
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: MainThread: I genStartup() Still receiving archive packets cnt:0 len:2
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: MainThread: I Using pc time adjusting archive record time by 8 sec 2020-04-08 02:07:00 CEST (1586304420) => 2020-04-08 02:07:08 CEST (1586304428)
Apr  8 02:09:09 raspberrypi weewx[566]: manager: Added record 2020-04-08 02:07:08 CEST (1586304428) to database 'weewx.sdb'
Apr  8 02:09:09 raspberrypi weewx[566]: engine: Main loop exiting. Shutting engine down.
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: Thread-4: I USB polling device thread exiting
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: MainThread: I USB polling thread expired
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: Thread-3: I Watchdog received shutdown
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: Thread-3: I Watchdog thread exiting
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: MainThread: I Watchdog thread expired
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: MainThread: I Received packet count live:4464 archive:2 control:465
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: MainThread: I Received bytes:936 sent bytes:48
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: MainThread: I Packet archive queue len:1 live queue len:1
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: MainThread: W Exiting with packets still in archive queue cnt:1
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: MainThread: W Exiting with packets still in live queue cnt:1
Apr  8 02:09:09 raspberrypi weewx[566]: wmr200: MainThread: I Driver gracefully exiting
Apr  8 02:09:09 raspberrypi weewx[566]: engine: Caught unrecoverable exception in engine:
Apr  8 02:09:09 raspberrypi weewx[566]:     ****  Non-positive value for record field 'interval': 0
Apr  8 02:09:09 raspberrypi weewx[566]:     ****  Traceback (most recent call last):
Apr  8 02:09:09 raspberrypi weewx[566]:     ****    File "/usr/share/weewx/weewx/engine.py", line 894, in main
Apr  8 02:09:09 raspberrypi weewx[566]:     ****      engine.run()
Apr  8 02:09:09 raspberrypi weewx[566]:     ****    File "/usr/share/weewx/weewx/engine.py", line 160, in run
Apr  8 02:09:09 raspberrypi weewx[566]:     ****      self.dispatchEvent(weewx.Event(weewx.STARTUP))
Apr  8 02:09:09 raspberrypi weewx[566]:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
Apr  8 02:09:09 raspberrypi weewx[566]:     ****      callback(event)
Apr  8 02:09:09 raspberrypi weewx[566]:     ****    File "/usr/share/weewx/weewx/engine.py", line 520, in startup
Apr  8 02:09:09 raspberrypi weewx[566]:     ****      self._catchup(self.engine.console.genStartupRecords)
Apr  8 02:09:09 raspberrypi weewx[566]:     ****    File "/usr/share/weewx/weewx/engine.py", line 635, in _catchup
Apr  8 02:09:09 raspberrypi weewx[566]:     ****      origin='hardware'))
Apr  8 02:09:09 raspberrypi weewx[566]:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
Apr  8 02:09:09 raspberrypi weewx[566]:     ****      callback(event)
Apr  8 02:09:09 raspberrypi weewx[566]:     ****    File "/usr/share/weewx/weewx/engine.py", line 601, in new_archive_record
Apr  8 02:09:09 raspberrypi weewx[566]:     ****      dbmanager.addRecord(event.record, accumulator=self.old_accumulator)
Apr  8 02:09:09 raspberrypi weewx[566]:     ****    File "/usr/share/weewx/weewx/manager.py", line 246, in addRecord
Apr  8 02:09:09 raspberrypi weewx[566]:     ****      self._addSingleRecord(record, cursor, log_level)
Apr  8 02:09:09 raspberrypi weewx[566]:     ****    File "/usr/share/weewx/weewx/manager.py", line 1212, in _addSingleRecord
Apr  8 02:09:09 raspberrypi weewx[566]:     ****      _weight = self._calc_weight(record)
Apr  8 02:09:09 raspberrypi weewx[566]:     ****    File "/usr/share/weewx/weewx/manager.py", line 1582, in _calc_weight
Apr  8 02:09:09 raspberrypi weewx[566]:     ****      raise ValueError("Non-positive value for record field 'interval': %s" % (record['interval'], ))
Apr  8 02:09:09 raspberrypi weewx[566]:     ****  ValueError: Non-positive value for record field 'interval': 0
Apr  8 02:09:09 raspberrypi weewx[566]:     ****  Exiting.
```

**Comment by superhet70** [comment]
> 
> 
> Michael, could you try this fix? [cmanton@47800a0](https://github.com/cmanton/weewx/commit/47800a0a622b7931898faf5aa6b254cac943557a)

You should try this patch. it has worked for my WMR200.

**Comment by tkeffer** [comment]
... or wait for V4.0, which will include the patch.

**Comment by Adri1G** [comment]
OK. Thank you :-)
